version: '3'
services:
  kitabikin-core-main:
    build:
      context: .
      dockerfile: .docker/main.dockerfile
    image: kitabikincom/kitabikin-core:main
    container_name: 'kitabikin-core-main'
    ports:
      - '18111:3000'
    env_file:
      - .env
    restart: always
    networks:
      - kitabikin-main-networks

networks:
  kitabikin-main-networks:
