version: '3'
services:
  kitabikin-core-local:
    build:
      context: .
      dockerfile: .docker/local.dockerfile
    image: rendiriz/kitabikin-core:local
    container_name: 'kitabikin-core-local'
    ports:
      - '1800:1800'
    env_file:
      - .env
    restart: always
    networks:
      - kitabikin-local-networks

networks:
  kitabikin-local-networks:
