@baseUrl = http://localhost:3000/
@version = v1
@endpoint = application

@username = {{$dotenv REST_KITABIKIN_USERNAME}}
@password = {{$dotenv REST_KITABIKIN_PASSWORD}}
@application = {{$dotenv REST_KITABIKIN_APPLICATION}}

### Login Service ==============================================================
# @name login

POST {{baseUrl}}{{version}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "application": "{{application}}"
}

#### Login Response
@token = {{login.response.body.data.token}}

### Total ======================================================================

GET {{baseUrl}}{{version}}/{{endpoint}}/total HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### List =======================================================================

GET {{baseUrl}}{{version}}/{{endpoint}}
    ?start=0
    &where[id_application__eq][0]=998726b6-4b3d-4ff8-a619-4ab1ae1ba366
    &where[id_application__eq][1]=8f725fb8-2c8a-4de9-89ea-c6e5f1173fbb
    &limit=2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Create =====================================================================
# @name create

POST {{baseUrl}}{{version}}/{{endpoint}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "test",
  "name": "Test",
  "description": "Test Description"
}

#### Create Response
@id = {{create.response.body.data.id_application}}

### Read =======================================================================

GET {{baseUrl}}{{version}}/{{endpoint}}/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Update =====================================================================

PUT {{baseUrl}}{{version}}/{{endpoint}}/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_application": "{{id}}",
  "code": "test-1",
  "name": "Test 1",
  "description": "Test 1 Description",
  "is_active": true
}

### Delete =====================================================================

PUT {{baseUrl}}{{version}}/{{endpoint}}/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_application": "{{id}}",
  "is_active": false
}